# SPDX-License-Identifier: AGPL-3.0-or-later
"""Attestation block — the trust product.

The attestation is the content hash of the pinned inputs, never of the rendered
document (which carries a report date). That preserves the property that the
same inputs always produce the same attestation, exactly the content-vs-metadata
split used throughout the engine. A reviewer can recompute the hash from the
pins and confirm the record was generated from the stated inputs.
"""

from __future__ import annotations

from typing import Any

from harness.hashing import content_hash
from harness.models.results import Pins, RunMeta
from harness.qms.baseline import QMS_BASELINE_REPO, QMS_BASELINE_TAG
from harness.version import ENGINE_VERSION

_DRAFT_NOTE = (
    "Draft evidence generated by the evaluation harness from pinned inputs. "
    "Requires human review, verdict confirmation, and signature before use as "
    "QMS evidence."
)
_MODEL_VERSION_NOTE = (
    "SUT and judge model_version are author-asserted. For a hosted endpoint that "
    "may update silently, pin a local model or record the provider's returned "
    "model id to keep this attestation trustworthy."
)


def build_attestation(pins: Pins, run_meta: RunMeta | None = None) -> dict[str, Any]:
    """Build the self-verifying attestation block for a QMS record."""
    pins_json = pins.model_dump(mode="json")
    block: dict[str, Any] = {
        "generated_by": f"harness-factory {ENGINE_VERSION}",
        "qms_baseline_tag": QMS_BASELINE_TAG,
        "qms_baseline_repo": QMS_BASELINE_REPO,
        "pinned_inputs_hash": content_hash(pins_json),
        "pins": pins_json,
        "draft_notice": _DRAFT_NOTE,
        "model_version_note": _MODEL_VERSION_NOTE,
    }
    if run_meta is not None:
        block["run_id"] = run_meta.run_id
        block["env_hash"] = run_meta.env_hash
        block["rendered_at"] = run_meta.timestamp  # run metadata; excluded from the hash
    return block


def unsigned_signoff(meaning: str, signer_roles: list[str]) -> dict[str, Any]:
    """A signature block left deliberately unsigned — the harness never approves."""
    return {
        "meaning_of_signature": meaning,
        "signer_roles": signer_roles,
        "signatures": [],  # populated by a human signer, not the harness
        "approval_reference": "",
    }
