# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render a validation dossier as GitHub-flavoured Markdown.

Markdown renders inline on GitHub (unlike HTML), so this is the format reviewers
read directly in a pull request. Same content as the printable HTML dossier;
status is text-labelled and information value is shown as a number plus a small
block bar (both render in any Markdown viewer, grayscale included).
"""

from __future__ import annotations

from typing import Any


def _bar(value, max_iv: float, width: int = 10) -> str:
    if value is None:
        return "— (not measured)"
    filled = 0 if max_iv <= 0 else round(value / max_iv * width)
    return f"`{'█' * filled}{'·' * (width - filled)}` {value:.3f}"


def render_dossier_md(d: dict[str, Any]) -> str:
    vv = d["vv_report"]
    s = vv["summary_of_results"]
    att = d["attestation"]
    contract_elems = d["contract"].get("elements", [])
    mss = d["contract"].get("minimal_sufficient_set_candidate", [])
    measured = [e["information_value"] for e in contract_elems
                if e.get("measured") and e.get("information_value") is not None]
    max_iv = max(measured) if measured else 0.0
    L: list[str] = []

    L.append(f"# Validation Dossier — {d['product_id']} v{d['product_version']}")
    L.append("")
    L.append(f"*Run `{d['run_id']}` · generated {d['generated_at']} · "
             f"QMS baseline {d['qms_baseline_tag']}*")
    L.append("")
    L.append(f"> **DRAFT — unsigned.** {att['draft_notice']} "
             f"Signing: {d['signing']['mechanism']} (not yet anchored).")
    L.append("")
    L.append(f"**Release recommendation: `{vv['release_recommendation']}`**")
    L.append("")
    L.append(f"_{d['intended_use']}_")

    L.append("\n## 1. Validation summary (baseline, intended input)")
    L.append(f"\n{s['passed']} / {s['total_test_cases']} rubric items passed · "
             f"{s['failed']} failed · condition: {s['condition']}\n")
    L.append("| Requirement (rubric item) | Result |")
    L.append("| --- | --- |")
    for item, status in s["per_test_case"].items():
        L.append(f"| {item} | `{status}` |")

    L.append("\n## 2. Acceptance criteria\n")
    results = d.get("acceptance", {}).get("results", [])
    if results:
        L.append("| Threshold | Value | Limit | Result |")
        L.append("| --- | --- | --- | --- |")
        for r in results:
            L.append(f"| {r['threshold']} | {r['value']} | {r['limit']} | "
                     f"`{'pass' if r['passed'] else 'fail'}` |")
    else:
        L.append("_none defined_")

    L.append("\n## 3. Input contract (characterization)\n")
    L.append("_Information value = mean score drop when the element is ablated. "
             "Characterization, not pass/fail._\n")
    L.append("| Element | Modality | Necessary | Information value |")
    L.append("| --- | --- | --- | --- |")
    for e in contract_elems:
        nec = "yes" if e["name"] in mss else "—"
        L.append(f"| {e['name']} | {e.get('modality','')} | {nec} | {_bar(e.get('information_value'), max_iv)} |")

    L.append("\n## 4. Judge calibration\n")
    cal = vv.get("calibration", {"status": "not_collected"})
    if cal.get("status") == "not_collected":
        L.append("Status: `not_collected` — no physician double-grading recorded yet.")
    else:
        g = cal.get("gate", {})
        o = cal.get("agreement", {}).get("overall", {})
        L.append(f"Gate: `{g.get('status','?')}` · overall κ = {o.get('kappa')} (n = {o.get('n')})")

    L.append("\n## 5. Attestation\n")
    L.append(f"Generated by **{att['generated_by']}**. "
             f"Pinned-inputs hash: `{att['pinned_inputs_hash']}`\n")
    L.append(f"_{att['model_version_note']}_\n")
    L.append("| Pinned input | Value |")
    L.append("| --- | --- |")
    for k, v in att["pins"].items():
        L.append(f"| {k} | `{v}` |")

    L.append("\n## 6. Signatures\n")
    sig = vv["signatures"]
    L.append(f"`unsigned` — meaning: {sig['meaning_of_signature']}. "
             f"Signer roles: {', '.join(sig['signer_roles'])}.")
    L.append(f"\n_Sign by review + anchoring to an immutable release "
             f"({d['signing']['mechanism']})._")
    L.append("")
    return "\n".join(L) + "\n"
