# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render structured QMS records into YAML / Markdown documents.

The structured record is the source of truth (and carries the attestation); the
rendered document is the human-readable artifact a reviewer signs. Rendering is
deterministic given the record.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


def render_yaml(record: dict[str, Any]) -> str:
    return yaml.safe_dump(record, sort_keys=False, allow_unicode=True)


def _kv(lines: list[str], label: str, value: Any) -> None:
    lines.append(f"- {label}: {value if value not in (None, '') else ''}")


def render_vv_report_md(record: dict[str, Any]) -> str:
    m = record["metadata"]
    s = record["summary_of_results"]
    scope = record["scope"]
    lines: list[str] = ["# Verification and Validation Report", "", "## Metadata"]
    _kv(lines, "Report ID", m["report_id"])
    _kv(lines, "Product ID", m["product_id"])
    _kv(lines, "Plan Reference", m["plan_reference"])
    _kv(lines, "Target Revision", m["target_revision"])
    _kv(lines, "Report Date", m["report_date"])
    _kv(lines, "Execution Mode", m["execution_mode"])

    lines += ["", "## Scope"]
    _kv(lines, "Activity Type", scope["activity_type"])
    _kv(lines, "Covered Requirements", ", ".join(scope["covered_requirements"]))
    _kv(lines, "Covered Risk Controls", ", ".join(scope["covered_risk_controls"]))
    _kv(lines, "Environment / Tooling", scope["environment_tooling_references"])
    _kv(lines, "Configuration Capture", scope["configuration_capture_references"])

    lines += ["", f"## Summary of Results ({s['condition']})"]
    _kv(lines, "Total Test Cases", s["total_test_cases"])
    _kv(lines, "Passed", s["passed"])
    _kv(lines, "Failed", s["failed"])
    _kv(lines, "Blocked", s["blocked"])
    _kv(lines, "Not Run", s["not_run"])
    lines.append("")
    lines.append("| Test Case | Status |")
    lines.append("| --- | --- |")
    for item_id, status in s["per_test_case"].items():
        lines.append(f"| {item_id} | {status} |")

    lines += ["", "## Characterization (not pass/fail)", ""]
    lines.append(record["characterization"]["note"])
    lines.append("")
    lines.append("| Element | Measured | Information Value |")
    lines.append("| --- | --- | --- |")
    for e in record["characterization"]["input_contract"]["elements"] or []:
        iv = e["information_value"]
        lines.append(f"| {e['name']} | {e['measured']} | {'' if iv is None else iv} |")

    lines += ["", "## Deviations and Open Issues"]
    if record["deviations_and_open_issues"]:
        for d in record["deviations_and_open_issues"]:
            lines.append(f"- {d['test_case_id']}: {d['status']}")
    else:
        lines.append("- None")

    rec = record["release_recommendation"]
    lines += ["", "## Release Recommendation"]
    lines.append(f"- [{'x' if rec == 'approved_for_release' else ' '}] Approved for release")
    lines.append("- [ ] Approved with restrictions")
    lines.append(
        f"- [{'x' if rec == 'not_approved_for_release' else ' '}] Not approved for release"
    )

    att = record["attestation"]
    lines += ["", "## Attestation"]
    _kv(lines, "Generated By", att["generated_by"])
    _kv(lines, "QMS Baseline", att["qms_baseline_tag"])
    _kv(lines, "Run ID", att.get("run_id"))
    _kv(lines, "Pinned Inputs Hash", att["pinned_inputs_hash"])
    _kv(lines, "Env Hash", att.get("env_hash"))
    lines.append(f"- {att['draft_notice']}")

    sig = record["signatures"]
    lines += ["", "## Signatures"]
    _kv(lines, "Meaning of Signature", sig["meaning_of_signature"])
    _kv(lines, "Signer Roles", ", ".join(sig["signer_roles"]))
    _kv(lines, "Signatures", "(unsigned — requires human approval)")
    return "\n".join(lines) + "\n"


def render_change_request_md(record: dict[str, Any]) -> str:
    m = record["metadata"]
    cs = record["change_summary"]
    ia = record["impact_assessment"]
    lines: list[str] = ["# Change Request and Impact Assessment", "", "## Metadata"]
    _kv(lines, "Change ID", m["change_id"])
    _kv(lines, "Product or Process ID", m["product_or_process_id"])
    _kv(lines, "Change Owner", m["change_owner"])
    _kv(lines, "Opened On", m["opened_on"])
    _kv(lines, "Change Type", m["change_type"])

    lines += ["", "## Change Summary"]
    _kv(lines, "Description", cs["description"])
    _kv(lines, "Rationale", cs["rationale"])
    _kv(lines, "Affected Baseline", cs["affected_baseline"])

    lines += ["", "## Impact Assessment"]
    _kv(lines, "Safety / Performance Impact", ia["safety_performance_impact"])
    if ia["regressed_elements"]:
        lines.append("- Regressed Elements:")
        for e in ia["regressed_elements"]:
            lines.append(f"  - {e}")
    _kv(lines, "Regulatory / Compliance Impact", ia["regulatory_compliance_impact"])
    _kv(lines, "Verification / Validation Impact", ia["verification_validation_impact"])
    _kv(lines, "Release Inclusion Decision", ia["release_inclusion_decision"])
    _kv(lines, "Binary Upgrade / Regression Impact", ia["binary_upgrade_regression_impact"])

    lines += ["", "## Attestation"]
    for role in ("baseline", "candidate"):
        att = record["attestation"][role]
        lines.append(f"- {role}: run pins hash {att['pinned_inputs_hash']}")
    lines.append(f"- {record['attestation']['baseline']['draft_notice']}")

    sig = record["signatures"]
    lines += ["", "## Signatures"]
    _kv(lines, "Meaning of Signature", sig["meaning_of_signature"])
    _kv(lines, "Signer Roles", ", ".join(sig["signer_roles"]))
    _kv(lines, "Signatures", "(unsigned — requires human approval)")
    return "\n".join(lines) + "\n"


def write_text(path: str | Path, text: str) -> None:
    Path(path).write_text(text, encoding="utf-8")
