# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit published content as JSON or a data-only TypeScript module.

The TypeScript emitter writes exactly one typed constant plus a generated-file
header (timestamp, engine version, pack pins, source run hashes) so the target
repo can prove where every byte came from — and a "do not grow logic here"
notice, because generated modules must stay data.
"""

from __future__ import annotations

import json
from typing import Any

from validrig.version import ENGINE_VERSION

_INDENT = "\t"


def _ts_string(s: str) -> str:
    """Emit a string as a TS template literal (readable multi-line HTML)."""
    escaped = s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return f"`{escaped}`"


def _ts_value(v: Any, depth: int) -> str:
    pad = _INDENT * depth
    inner = _INDENT * (depth + 1)
    if isinstance(v, str):
        return _ts_string(v)
    if isinstance(v, bool):
        return "true" if v else "false"
    if v is None:
        return "null"
    if isinstance(v, (int, float)):
        return json.dumps(v)
    if isinstance(v, dict):
        rows = [f"{inner}{json.dumps(k) if not k.isidentifier() else k}: {_ts_value(val, depth + 1)},"
                for k, val in v.items()]
        return "{\n" + "\n".join(rows) + f"\n{pad}}}"
    if isinstance(v, list):
        rows = [f"{inner}{_ts_value(val, depth + 1)}," for val in v]
        return "[\n" + "\n".join(rows) + f"\n{pad}]"
    raise TypeError(f"cannot emit value of type {type(v)!r}")


def emit_ts(
    content: dict[str, Any],
    meta: dict[str, Any],
    generated_at: str,
    type_name: str = "PipelineContent",
    types_module: str = "./types",
) -> str:
    runs = "\n".join(
        f"//   run {r} (sut: {meta['run_suts'].get(r, '?')})" for r in meta["run_ids"]
    )
    header = f"""// GENERATED by `rig publish` — do not grow logic here, do not edit by hand.
// Regenerate from the pinned runs to change anything on this page.
//
// engine:    validrig {ENGINE_VERSION}
// generated: {generated_at}
// pack:      {meta['pack_id']} v{meta['pack_version']} (pack_hash {meta['pack_hash']})
// source runs:
{runs}
"""
    body = _ts_value(content, 0)
    return (
        f"{header}\nimport type {{ {type_name} }} from '{types_module}';\n\n"
        f"export const {meta['export_name']}: {type_name} = {body};\n"
    )


def emit_json(content: dict[str, Any]) -> str:
    return json.dumps(content, indent=2, ensure_ascii=False, sort_keys=False) + "\n"
