# SPDX-License-Identifier: AGPL-3.0-or-later
"""Render a validation dossier as an embeddable HTML *fragment*.

Same content as the printable dossier page (``dossier_html``) but with no
document skeleton, inline CSS, or scripts — headings (h3/h4), paragraphs, and
tables only, so a host page can embed the real dossier inside its own sheet
styling. Nothing is summarized away: validation summary, acceptance criteria,
input contract, calibration, attestation (run hash + engine version), and the
signature state all appear.
"""

from __future__ import annotations

import html
from typing import Any


def _e(v: Any) -> str:
    return html.escape(str(v))


def _iv(value: Any) -> str:
    return "not measured" if value is None else f"{value:.3f}"


def render_dossier_fragment(d: dict[str, Any]) -> str:
    vv = d["vv_report"]
    s = vv["summary_of_results"]
    att = d["attestation"]
    contract = d.get("contract", {})
    elems = contract.get("elements", [])
    mss = contract.get("minimal_sufficient_set_candidate", [])
    L: list[str] = []

    L.append(
        f"<p><em>Draft evidence, unsigned — generated by the engine from pinned "
        f"inputs; requires human review and signature before use as QMS evidence.</em> "
        f"Release recommendation: <strong>{_e(vv['release_recommendation'])}</strong></p>"
    )
    L.append(f"<p>{_e(d['intended_use'])}</p>")

    L.append("<h3>1. Validation summary (baseline, intended input)</h3>")
    L.append(
        f"<p>{_e(s['passed'])} / {_e(s['total_test_cases'])} rubric items passed &middot; "
        f"{_e(s['failed'])} failed &middot; condition: {_e(s['condition'])}</p>"
    )
    L.append("<table><thead><tr><th>Requirement (rubric item)</th><th>Result</th></tr></thead><tbody>")
    for item, status in s["per_test_case"].items():
        L.append(f"<tr><td>{_e(item)}</td><td>{_e(status)}</td></tr>")
    L.append("</tbody></table>")

    L.append("<h3>2. Acceptance criteria</h3>")
    results = d.get("acceptance", {}).get("results", [])
    if results:
        L.append(
            "<table><thead><tr><th>Threshold</th><th>Value</th><th>Limit</th>"
            "<th>Result</th></tr></thead><tbody>"
        )
        for r in results:
            L.append(
                f"<tr><td>{_e(r['threshold'])}</td><td>{_e(round(r['value'], 4))}</td>"
                f"<td>{_e(r['limit'])}</td>"
                f"<td><strong>{'PASS' if r['passed'] else 'FAIL'}</strong></td></tr>"
            )
        L.append("</tbody></table>")
    else:
        L.append("<p>none defined</p>")

    L.append("<h3>3. Input contract (characterization)</h3>")
    L.append(
        "<p>Information value = mean score drop when the element is withheld. "
        "Characterization, not pass/fail.</p>"
    )
    L.append(
        "<table><thead><tr><th>Element</th><th>Modality</th><th>Necessary</th>"
        "<th>Information value</th></tr></thead><tbody>"
    )
    for e in elems:
        nec = "yes" if e["name"] in mss else "&mdash;"
        L.append(
            f"<tr><td>{_e(e['name'])}</td><td>{_e(e.get('modality', ''))}</td>"
            f"<td>{nec}</td><td>{_e(_iv(e.get('information_value')))}</td></tr>"
        )
    L.append("</tbody></table>")

    L.append("<h3>4. Judge calibration</h3>")
    cal = vv.get("calibration") or {"status": "not_collected"}
    if cal.get("status") == "not_collected":
        L.append("<p>Status: not_collected &mdash; no physician double-grading recorded yet.</p>")
    else:
        g = cal.get("gate", {})
        o = cal.get("agreement", {}).get("overall", {})
        L.append(
            f"<p>Gate: {_e(g.get('status', '?'))} &middot; overall &kappa; = "
            f"{_e(o.get('kappa'))} (n = {_e(o.get('n'))})</p>"
        )

    L.append("<h3>5. Attestation</h3>")
    L.append(
        f"<p>Generated by <strong>{_e(att['generated_by'])}</strong>. "
        f"Pinned-inputs hash: <code>{_e(att['pinned_inputs_hash'])}</code></p>"
    )
    L.append(f"<p><em>{_e(att['model_version_note'])}</em></p>")
    L.append("<table><thead><tr><th>Pinned input</th><th>Value</th></tr></thead><tbody>")
    for k, v in att["pins"].items():
        L.append(f"<tr><td>{_e(k)}</td><td><code>{_e(v)}</code></td></tr>")
    L.append("</tbody></table>")

    L.append("<h3>6. Signatures</h3>")
    sig = vv["signatures"]
    L.append(
        f"<p>unsigned &mdash; meaning: {_e(sig['meaning_of_signature'])}. "
        f"Signer roles: {_e(', '.join(sig['signer_roles']))}. "
        f"Sign by review + anchoring to an immutable release "
        f"({_e(d['signing']['mechanism'])}).</p>"
    )
    return "\n".join(L) + "\n"
